definitions:
  main.ReturnModel:
    properties:
      id:
        type: string
      name:
        type: string
      property:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample API.
  title: Ping API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.ReturnModel'
      summary: ping example
      tags:
      - example
swagger: "2.0"
